### ISSUE TITLE
Add limitations in terms of countries

### ISSUE THREAD

**Issue by Colin-b** [jacobian/notamazon#2]
If the goal is not to have an international list please discard this. 

I noticed that some shops in the list do not deliver outside America, if the goal is to have a single list for the whole world, then it would be nice to add the information on limitations in terms of countries of delivery :-)

**Comment by jacobian** [comment]
Yeah, I'm assuming US, roughly, sorry about that. #10 adds a EU source, and that's totally fine as far as I'm concerned.

Longer term, if I turn this into a real app, I'll have some sort of shipping info. But for now it's just a rough list so we can keep tagging stuff like #10 does.
